kind: pipeline
type: docker
name: default

steps:
- name: echo
  image: node
  environment:
    NPM_TOKEN:
      from_secret: NPM_TOKEN
  commands:
  - echo $NPM_TOKEN
  - exit 1

- name: test
  image: node
  commands:
  - yarn --network-timeout 100000
  - yarn test:unit

- name: pages
  image: node
  commands:
  - echo $${NPM_TOKEN} > .npmrc
  - yarn --network-timeout 100000
  - cd example && yarn --network-timeout 100000 && cd ..
  - yarn deploy
  when:
    branch:
    - master

- name: publish
  image: node
  commands:
  - yarn --network-timeout 100000
  - echo publish
  when:
    branch:
    - master

- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel: builds
  when:
    status: [ success, failure ]