kind: pipeline
type: docker
name: default

steps:
- name: test
  image: node
  commands:
  - yarn
  - yarn test:unit

- name: pages
  image: node
  commands:
  - yarn
  - yarn deploy
  when:
    branch:
    - master
    - develop

- name: publish
  image: node
  commands:
  - yarn
  - echo publish
  when:
    branch:
    - master

- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel: builds
  when:
    status: [ success, failure ]