kind: pipeline
type: docker
name: default

steps:
- name: Unit Testing
  image: node
  commands:
  - yarn --network-timeout 100000
  - yarn test:unit

- name: Build Example App
  image: node
  commands:
  - yarn --network-timeout 100000
  - cd example && yarn --network-timeout 100000 && cd ..
  # when:
  #   branch:
  #   - master

- name: Deploy to GitHub Pages
  image: plugins/gh-pages
  settings:
    username:
      from_secret: github_username
    password:
      from_secret: github_password
    pages_directory: example/build
  # when:
  #   branch:
  #   - master

- name: Publish to NPM
  image: node
  environment:
    NPM_TOKEN:
      from_secret: NPM_TOKEN
  commands:
  - yarn --network-timeout 100000
  - echo publish
  when:
    branch:
    - master

- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel: builds
  when:
    status: [ success, failure ]